# Generated by Django 4.1.7 on 2023-07-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='post_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
